name: testtask CI pipeline
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven


      - name: Build with Maven
        run: mvn clean install --batch-mode

      - name: Run tests
        run: mvn test

      - name: Generate code coverage report
        run: mvn jacoco:report

      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: surefire-report
          path: target/surefire-reports/

      - name: Upload JaCoCo report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco/